### ISSUE TITLE
[charts/redis-ha][BUG] pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by the-nw1-group** [DandyDeveloper/charts#11]
**Describe the bug**
After running:

```
helm install dandydev/redis-ha
helm install redis-ha dandydev/redis-ha
```

I get the following error/events: 

```
running "VolumeBinding" filter plugin for pod "redis-ha-server-1": pod has unbound immediate PersistentVolumeClaims
running "VolumeBinding" filter plugin for pod "redis-ha-server-1": pod has unbound immediate PersistentVolumeClaims
0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules.
```

And ` redis-ha-server-1` fails to start. 

**To Reproduce**
1. `helm install dandydev/redis-ha`
2. `helm install redis-ha dandydev/redis-ha`
3. See error

**Expected behavior**
For it to work :-D

**Additional context**
I'm running on minikube (v1.9.0) with kvm2 on centos 7 box. 
kubectl version version is v1.18.0, and helm version v3.1.2

**Comment by the-nw1-group** [comment]
Seems to be associated with this [issue on](https://github.com/kubernetes/minikube/issues/3869) minikube. So happy to close here, and raise on minikube.

**Comment by DandyDeveloper** [comment]
@the-nw1-group It's less of an issue and more of a "feature". Because HA implies that each pod should be deployed to a isolated node (physical machine) and Minikube only deploys with a single node instance, it means we can't actually deploy as expected based on the affinities defined in the Redis resources. 

Best thing to do is update the deployed resources and just remove the affinities. That should fix it.

**Comment by the-nw1-group** [comment]
Many thanks - that sorted it. As is probably apparent this is all a little new to me.
