### ISSUE TITLE
[chart/redis-ha][REQUEST] Seprate `StatefulSet`s for redis and sentinel

### ISSUE THREAD

**Issue by tahajahangir** [DandyDeveloper/charts#129]
Number of redis servers is not related to sentinel servers, we can have 2 or 4 redis servers (e.g. on large deployments we want to run only 1 slave, not 2).

Also it's better to not tie redis-servers to sentinel. A cluster with 3 redis servers and 3 sentinel servers, can tolerate losing 2 redis servers, but cannot continue to work with only 1 sentinel.

So I suggest splitting the current `StatefulSet` into two.

**Comment by DandyDeveloper** [comment]
I wish I could remember why the original creator of this chart did that, I think it was based on an original implementation.

I think I need more input from others on this, because whilst this isn't incorrect. What's the disadvantage to having an even number of sentinels to Redis instances?

Assuming quorum can be attained.

**Comment by silvpol** [comment]
I would suggest that Kyle Kingsbury's (Aphyr) article had something to do with it. Have a look at the section titled "Redis Strategies".  [Jepsen: Redis](https://aphyr.com/posts/283-jepsen-redis)

I don't have a source to quote here, but recall that in the past Redis' author was advising against colocating Redis and Sentinel. Now that setup is part of official documentation. [Sentinel Docs](https://redis.io/topics/sentinel#example-2-basic-setup-with-three-boxes)

I think both modes are possible if Sentinel is separated out of StatefulSet, if you want them colocated just set affinity and anti-affinity so that Sentinels land on the same nodes as Redis but repel each other.

**Comment by DandyDeveloper** [comment]
@tahajahangir @silvpol I feel like at this stage then, based purely on how the maintainers recommend configuration. It would be better to stick with the model we have.

Unless there are some clear disadvantages to doing so, I don't see a clear benefit to managing this. It forces people to be more cluster aware if we change this because they have to make sure affinities aren't in some way preventing scheduling on their cluster which even in the chart could be a ballache. 

Whereas current implementation has a Sentinel per instance, which for MOST cases (3) is exactly what is recommended by Redis.

The only disadvantage as mentioned by the OP is if we lose a node, we lose Redis and Sentinel but would this not be the case if we had 2 separate statefulsets anyway? I'm happy to hear arguments against this by the way. I've been so OOTL with Redis recently, I'm happy to have my mind changed.

**Comment by tahajahangir** [comment]
The main reason for me is 1) large deployments 2) more reasonable structure

1) With a 70GB Redis instance (which requires even more RAM because of replication/bgsave), 2 redis instances is enought for HA, and having a third instance requires notable resources.

2) By default, these are two separate services (in the microservice/12factor terminology). And by default each microservice should be a seprate workload (deployment/statefullset). We should have a reason for merging these two services into one statefullset.

**Comment by silvpol** [comment]
@tahajahangir 
1. At this instance size I can see why would you want that
2. True that they are separate microservices, but they are not really independent. Did you check Aphyr's article I mentioned? The recommendation is to align topologies to avoid edge cases. When two containers are in same pod the communication is down to kernel moving memory around, with separation you can end up with sentinel that can't talk to redis despite both being reachable independently. In the interest of transparency, Antirez (Redis' author) [replied](http://antirez.com/news/55) to the test, please check it out.

I'm not fundamentally against making the change, but I think it's likely to introduce new failure modes and would involve significant chart refactoring. Alternative approach would be to add ability to remove sentinel from the set to that you can plug in your own setup.

**Comment by DandyDeveloper** [comment]
I think for the time being, I'll keep this in the backlog for now and consider this during AFTER another refactor.

Right now, I'm more concerned that this chart isn't robust enough for all scenarios and also maybe overcomplicated to a fault. 

I just need to find time for a major refactor.

**Comment by DandyDeveloper** [comment]
Housekeeping and closing this. Coming back, I don't think we'll action this for now. Welcome submissions with ways to implement this appropriately but its just not something I'm going to be doing and more specifically, doesn't seem to be the right direction for the chart.
