### ISSUE TITLE
/chart/redis-ha For ha proxy service, there is no port 26379 for sentinel connection

### ISSUE THREAD

**Issue by RoyKimYYZ** [DandyDeveloper/charts#84]
**Describe the bug**
I'm using StackExchange.redis and have been using bitnami redis helm chart, but I like redis-ha as it handles pod failure. I don't understand HA-proxy service. Shouldn't there be a port for 26379 for sentinel connection along with port 6379? bitnami helm chart follows this model. 

**To Reproduce**
1. Install helm chart with default redis values.yaml

**Expected behavior**
For ha proxy service, there is no port 26379 for sentinel connection

**Additional context**
Maybe this is feature request?

**Comment by DandyDeveloper** [comment]
@RoyKimYYZ The objective of HAProxy was to expose the Redis instance and determine the master, effectively bypassing the need for Sentinel for external access (whilst still retaining the benefits of Sentinel). 

I don't see a good reason for NOT including the Sentinel in HAProxy, it just wasn't by design originally. 

Presumably you would just expect this to use the `redis` service and roundrobin the Sentinel on all instances, OR would you expect this to point at the Sentinel currently assigned to master?

**Comment by RoyKimYYZ** [comment]
@DandyDeveloper Thanks for clarification on HAProxy design. In my web application deployed inside the kubernetes cluster and using StackExchange.Redis (C#,.net core). So just now, I tried to set the Connection endpoint to <appname>-redis-ha-haproxy.redis:6379. However, I get an application error in my app logs

_**The ConnectionMultiplexer is not a Sentinel connection.
   at StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config,**_

Yesterday, I can get the redis/sentinel connection to work with my app using the headless service name with port 26379.

**Comment by RoyKimYYZ** [comment]
I am now able to have my application connect via HA Proxy by removing the configuration servicename setting so that the connection is not sentinel mode. This is on the app config side of StackExchange.Redis.

So before closing issue, what is material benefit of HA proxy vs connecting directly to headless service? The app is hosted inside kubernetes so no need to access externally.

**Comment by DandyDeveloper** [comment]
@RoyKimYYZ Sorry I haven't gotten back faster. 

I should preface this by saying - The objective of including HAProxy was to support external access to the Redis cluster, as the architectural design of Redis does NOT allow for an easy way to expose the elected master from within Kubernetes. 

The Headless service will roundrobin across all the instances, 2 of which would be replicas. Resulting in inserts to fail. It has some other overhead that I don't remember with regards to exposing it from outside a cluster.

HAProxy on the other hand takes the overhead of determining which Redis instance is primary and just gives a direct tunnel to the elected master from both within and outside the cluster. 

HAProxy is specifically added to externally access Redis, but can also replace the need to ask Sentinel internally. Any internal communication should use the headless service and asking Sentinel for the client address (The standard workflow for Sentinel + Redis)

If you think the above satisfies the questions being asked, please feel free to close this issue.

**Comment by RoyKimYYZ** [comment]
Thank you!

**Comment by paranoidsp** [comment]
Sorry for resurrecting this, but I have a slightly unrelated question for which this might be a good place. 

I'm looking for a smooth way to migrate some existing redis clusters into EKS into the redis-ha chart. This will involve adding the sentinel pods and redis slaves to an external master, and then performing a failover. I'm considering doing this via hostNetwork on the pods, but it's not entirely straightforward.

Another option is some haproxy shenanigans in order to access the sentinel inside the cluster, but sentinel communication breaks down since it happens via advertised IP:port combos.

@DandyDeveloper do you have any suggestions?
